environment:
  global:
    MSYS2_BASEVER: 20150512

  matrix:
  - TARGET: x86_64-pc-windows-msvc
    MSYS2_ARCH: x86_64
  - TARGET: i686-pc-windows-gnu
    MSYS2_ARCH: i686

install:
  - appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
  - 7z x msys2.tar.xz
  - 7z x msys2.tar > NUL
  - msys64\msys2_shell.bat
  - pacman -Sy
  - pacman --needed --noconfirm -Sy bash pacman pacman-mirrors msys2-runtime
  - pacman -S mingw-w64-%MSYS2_ARCH%-toolchain
  - pacman -S base-devel
  - exit
  - msys64\msys2_shell.bat
  - pacman -Su
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - make -v

build_script:
  - make

test_script:
  - make test
